---
- name: Deploy Node.js app with Nginx and Let's Encrypt on Ubuntu 22.04
  hosts: staging-bh:production-bh:production-fr:staging-bh-next
  become: yes
  roles:
    - setup
    - nginx
    - https
    - nodejs
    - github
    - application

- name: Deploy Wordpress with Nginx and Let's Encrypt on Ubuntu 22.04
  hosts: management-bh
  become: yes
  roles:
    # - setup
    # - nginx
    # - https
    # - nodejs
    # - github
    # - php
    #- mysql
    # - wordpress
    - nginx-wp
