- name: Ensure Python 3 is installed
  apt:
    name: python3
    state: present
    update_cache: yes

- name: Install pip for Python 3
  apt:
    name: python3-pip
    state: present

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    update_password: always
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MySQL database
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_password: "{{ mysql_root_password }}"
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MySQL user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
    login_password: "{{ mysql_root_password }}"
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock